name 'install-packages'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures install-packages'
long_description 'Installs/Configures install-packages'
version '0.1.0'
