---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.1
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[motd_rhel::default]
    attributes:
